service: alastrialandia

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    ISSUERS: ${ssm:/alastrialandia/${opt:stage}/issuers~true}

custom:
  serverless-offline:
    port: 3001
  kms:
    keyId:
      Ref: AlastrialandiaKey
  scriptHooks:
     aws:deploy:finalize:cleanup: npm run deploy-secrets #once secrets are set this can be commented out.

plugins:
  - serverless-express
  - serverless-scriptable-plugin
  - serverless-plugin-include-dependencies
  - serverless-offline

functions:
  server:
    handler: src/server.handler
    timeout: 12
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors:
            origins:
              - https://alastrialandia.uport.me
              - https://alastrialandia.uport.space
            allowCredentials: false
            headers:
              - Content-Type

package:
  exclude:
    - ./**
  include:
    - src/server.js

resources:
  Resources:
     AlastrialandiaKey:
      Type: AWS::KMS::Key
      Properties:
        Description: "Alastrialandia KMS key"
        KeyPolicy:
          Version: "2012-10-17"
          Id: "key-default-1"
          Statement:
            -
              Sid: "Allow administration of the key"
              Effect: "Allow"
              Principal:
                AWS: { "Fn::Join" : ["" , ["arn:aws:iam::", {"Ref" : "AWS::AccountId"} ,":root" ]] }
              Action:
                - "kms:*"
              Resource: "*"
